name: Scan

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ] 
  workflow_dispatch:
    inputs:
      Name:   
        required: true
        default: 'Re-run the workflow'
      Description:
        default: ''  


jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD }}